### Pandas Basic 

In [3]:
import numpy as np
list_ = [1,2,3,4,5]
array_list = np.array(object = list_)

In [2]:
array_list

array([1, 2, 3, 4, 5])

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes there is a difference between list_ and array_list list_ is a data type of python list and array_list is a data type of array in numpy

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [9]:
for i in list_:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [10]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


Q3. Considering the following changes in the variable, array_list:
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [16]:
array_list = np.array(object = list_, dtype = int)

No there is no change in data type of both the variable

In [14]:
[type(i) for i in list_]

[int, int, int, int, int]

In [15]:
[type(i) for i in array_list]

[numpy.int32, numpy.int32, numpy.int32, numpy.int32, numpy.int32]

In [17]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [19]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
num_array.shape   #It is a 2x3 matrix

(2, 3)

In [21]:
num_array.size  #Total elemnt present in this num_array is 6

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [25]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.random.randint(0,1,(3,3))

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
data1=np.diag([1,1,1,1,1,])

In [29]:
data1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])